# Generated by Django 5.1.1 on 2024-09-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AidPrograms',
            fields=[
                ('programId', models.AutoField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=255)),
                ('programDescription', models.TextField()),
                ('programType', models.CharField(max_length=50)),
                ('programContact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesAndTips',
            fields=[
                ('articleTipId', models.AutoField(primary_key=True, serialize=False)),
                ('articleTipTitle', models.CharField(max_length=255)),
                ('articleTipContent', models.TextField()),
                ('articleTipType', models.CharField(max_length=50)),
                ('articleTipPublicationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('childId', models.AutoField(primary_key=True, serialize=False)),
                ('childName', models.CharField(max_length=50)),
                ('childLastName', models.CharField(max_length=50)),
                ('childAgeMonth', models.IntegerField()),
                ('childGender', models.BooleanField()),
                ('childCurrentWeight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('childCurrentHeight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTips',
            fields=[
                ('dailyTipId', models.AutoField(primary_key=True, serialize=False)),
                ('dailyTipContent', models.TextField()),
                ('dailyTipDate', models.DateField()),
                ('dailyTipCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCenters',
            fields=[
                ('healthCenterId', models.AutoField(primary_key=True, serialize=False)),
                ('healthCenterName', models.CharField(max_length=255)),
                ('healthCenterAddress', models.CharField(max_length=255)),
                ('healthCenterEmail', models.EmailField(max_length=255)),
                ('healthCenterPhone', models.CharField(max_length=20)),
                ('healthCenterContactPerson', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyTips',
            fields=[
                ('pregnancyTipId', models.AutoField(primary_key=True, serialize=False)),
                ('pregnancyTipContent', models.TextField()),
                ('pregnancyTipStage', models.CharField(max_length=50)),
                ('pregnancyTipDate', models.DateField()),
                ('pregnancyTipCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipeId', models.AutoField(primary_key=True, serialize=False)),
                ('recipeName', models.CharField(max_length=255)),
                ('recipeDescription', models.CharField(max_length=255)),
                ('recipeIngredients', models.CharField(max_length=255)),
                ('recipeInstructions', models.CharField(max_length=255)),
                ('recipeEstimatedPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userFirstName', models.CharField(max_length=50)),
                ('userLastName', models.CharField(max_length=50)),
                ('userPassword', models.CharField(max_length=255)),
                ('userDNI', models.CharField(max_length=8)),
                ('userPhone', models.CharField(max_length=9)),
                ('userEmail', models.EmailField(max_length=255)),
                ('userRegistrationDate', models.DateField()),
                ('UserPlace', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthReports',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('reportDate', models.DateField()),
                ('reportDescription', models.TextField()),
                ('reportUrl', models.CharField(max_length=255)),
                ('childId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriscan.child')),
            ],
        ),
        migrations.CreateModel(
            name='MalnutritionDetection',
            fields=[
                ('detectionId', models.AutoField(primary_key=True, serialize=False)),
                ('detectionDate', models.DateField()),
                ('detectionResult', models.CharField(max_length=50)),
                ('detectionImageUrl', models.CharField(max_length=255)),
                ('childId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriscan.child')),
                ('healthCenterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriscan.healthcenters')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalRecommendations',
            fields=[
                ('recommendationId', models.AutoField(primary_key=True, serialize=False)),
                ('recommendationTitle', models.CharField(max_length=255)),
                ('recommendationDescription', models.TextField()),
                ('recommendationType', models.CharField(max_length=50)),
                ('childId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriscan.child')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationId', models.AutoField(primary_key=True, serialize=False)),
                ('notificationTitle', models.CharField(max_length=255)),
                ('notificationDescription', models.TextField()),
                ('notificationDate', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriscan.user')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriscan.user'),
        ),
        migrations.CreateModel(
            name='RecommendationRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrrecommendationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriscan.nutritionalrecommendations')),
                ('recipeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriscan.recipes')),
            ],
            options={
                'unique_together': {('recipeId', 'nutrrecommendationId')},
            },
        ),
    ]
