# Generated by Django 5.1.1 on 2024-11-07 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Desnutricion severa', 'Desnutricion severa'), ('Normal', 'Normal'), ('Riesgo desnutricion', 'Riesgo desnutricion')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AditionalInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDNI', models.CharField(max_length=8, unique=True)),
                ('userPhone', models.CharField(max_length=9, unique=True)),
                ('userPlace', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('childId', models.AutoField(primary_key=True, serialize=False)),
                ('childName', models.CharField(max_length=50)),
                ('childLastName', models.CharField(max_length=50)),
                ('childAgeMonth', models.IntegerField()),
                ('childGender', models.BooleanField()),
                ('childCurrentWeight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('childCurrentHeight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('childBirthDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MalnutritionDetection',
            fields=[
                ('detectionId', models.AutoField(primary_key=True, serialize=False)),
                ('detectionDate', models.DateField(auto_now_add=True)),
                ('detectionResult', models.CharField(max_length=50)),
                ('detectionImageUrl', models.URLField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='nutriscan.child')),
            ],
        ),
        migrations.CreateModel(
            name='ImmediateRecommendation',
            fields=[
                ('inmediateRecomId', models.AutoField(primary_key=True, serialize=False)),
                ('inmediateRecomMessage', models.TextField()),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immediate_recommendation', to='nutriscan.malnutritiondetection')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationTitle', models.CharField(max_length=255)),
                ('notificationDescription', models.TextField()),
                ('notificationDate', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expiration', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
